# Native iOS toolchain for the P.T. PC port.
# Usage: cmake -S . -B build-ios -G Xcode -DCMAKE_TOOLCHAIN_FILE=cmake/iOS.cmake
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "iOS device SDK")
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "iOS device architecture")
set(CMAKE_OSX_DEPLOYMENT_TARGET 16.0 CACHE STRING "Minimum iOS version")
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS iphoneos CACHE STRING "")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED NO CACHE STRING "")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO CACHE STRING "")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CMAKE_OSX_SYSROOT CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET)
